### ISSUE TITLE
Python 3.7 support: async is a keyword

### ISSUE THREAD

**Issue by MaksimTitenko** [wgnet/aiohttp_baseapi#2]
SyntaxError in python 3.7
`async` has become a keyword in Python 3.7 and can not be used as an argument name.
![aiopg_error_from_github](https://user-images.githubusercontent.com/38699903/55383991-2e002d00-5532-11e9-9c21-9de9ce92c986.png)

**Comment by dburakov** [comment]
Probably you have installed an old version of psycopg, see https://github.com/psycopg/psycopg2/issues/714
